[project]
name = "crawl-post-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.9.0"
dependencies = [
    "aiohttp==3.7.4",
    "beautifulsoup4==4.9.3",
    "requests==2.25.1",
]
